[project]
name = "licra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "charudatta10", email = "100494c@gmail.com" }
]
requires-python = ">=3.10.6"
dependencies = [
    "git-filter-repo>=2.47.0",
]

[project.scripts]
licra = "licra:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
